name: SuperCauldrons
main: us.hinchy.SuperCauldrons.SuperCauldrons
version: 1.2.4
description: Adds useful features to the Cauldron block.
author: Zach Hinchy
website: http://dev.bukkit.org/server-mods/supercauldrons/
commands:
   screload:
      description: This is the command to reload the SuperCauldrons config.
      permission: supercauldrons.reload
      usage: /screload